export const grid2Data = [
    { Id: 1, name: 'Alice', prof: "Engineer", sub: "Azure" },
    { Id: 2, name: 'Bob', prof: "Analyst", sub: "AWS" },
    { Id: 3, name: 'Charlie', prof: "Consultant", sub: "GCP" },
    { Id: 4, name: 'Daisy', prof: "Developer", sub: "Azure" },
    { Id: 5, name: 'Ethan', prof: "Manager", sub: "SAP" },
    { Id: 6, name: 'Fiona', prof: "Architect", sub: "Oracle" },
    { Id: 7, name: 'George', prof: "Analyst", sub: "AWS" },
    { Id: 8, name: 'Hannah', prof: "Engineer", sub: "Google Cloud" },
    { Id: 9, name: 'Ivan', prof: "Consultant", sub: "Azure" },
    { Id: 10, name: 'Jill', prof: "Developer", sub: "GCP" },
    { Id: 11, name: 'Kevin', prof: "Manager", sub: "Azure" },
    { Id: 12, name: 'Lily', prof: "Engineer", sub: "AWS" },
    { Id: 13, name: 'Mike', prof: "Consultant", sub: "SAP" },
    { Id: 14, name: 'Nina', prof: "Analyst", sub: "Google Cloud" },
    { Id: 15, name: 'Oscar', prof: "Architect", sub: "Oracle" },
    { Id: 16, name: 'Paul', prof: "Engineer", sub: "Azure" },
    { Id: 17, name: 'Quinn', prof: "Developer", sub: "AWS" },
    { Id: 18, name: 'Rachel', prof: "Consultant", sub: "GCP" },
    { Id: 19, name: 'Sam', prof: "Manager", sub: "Azure" },
    { Id: 20, name: 'Tina', prof: "Analyst", sub: "SAP" },
    { Id: 21, name: 'Uma', prof: "Developer", sub: "Oracle" },
    { Id: 22, name: 'Victor', prof: "Engineer", sub: "AWS" },
    { Id: 23, name: 'Wendy', prof: "Consultant", sub: "Google Cloud" },
    { Id: 24, name: 'Xander', prof: "Analyst", sub: "Azure" },
    { Id: 25, name: 'Yara', prof: "Architect", sub: "SAP" },
    { Id: 26, name: 'Zane', prof: "Manager", sub: "AWS" },
    { Id: 27, name: 'Amelia', prof: "Engineer", sub: "Google Cloud" },
    { Id: 28, name: 'Blake', prof: "Consultant", sub: "Oracle" },
    { Id: 29, name: 'Cara', prof: "Analyst", sub: "GCP" },
    { Id: 30, name: 'Derek', prof: "Developer", sub: "Azure" },
    { Id: 31, name: 'Eva', prof: "Manager", sub: "SAP" },
    { Id: 32, name: 'Frank', prof: "Engineer", sub: "AWS" },
    { Id: 33, name: 'Grace', prof: "Consultant", sub: "Oracle" },
    { Id: 34, name: 'Henry', prof: "Analyst", sub: "Google Cloud" },
    { Id: 35, name: 'Ivy', prof: "Architect", sub: "Azure" },
    { Id: 36, name: 'Jack', prof: "Developer", sub: "GCP" },
    { Id: 37, name: 'Kara', prof: "Engineer", sub: "AWS" },
    { Id: 38, name: 'Leo', prof: "Consultant", sub: "SAP" },
    { Id: 39, name: 'Mona', prof: "Analyst", sub: "Oracle" },
    { Id: 40, name: 'Ned', prof: "Developer", sub: "Google Cloud" },
    { Id: 41, name: 'Olga', prof: "Engineer", sub: "Azure" },
    { Id: 42, name: 'Pete', prof: "Manager", sub: "AWS" },
    { Id: 43, name: 'Rita', prof: "Consultant", sub: "Oracle" },
    { Id: 44, name: 'Scott', prof: "Analyst", sub: "GCP" },
    { Id: 45, name: 'Tara', prof: "Architect", sub: "Azure" },
    { Id: 46, name: 'Umar', prof: "Developer", sub: "Google Cloud" },
    { Id: 47, name: 'Vera', prof: "Engineer", sub: "SAP" },
    { Id: 48, name: 'Will', prof: "Consultant", sub: "AWS" },
    { Id: 49, name: 'Xena', prof: "Analyst", sub: "Azure" },
    { Id: 50, name: 'Yusuf', prof: "Manager", sub: "Google Cloud" },
    { Id: 51, name: 'Zara', prof: "Engineer", sub: "Oracle" },
    { Id: 52, name: 'Alan', prof: "Developer", sub: "SAP" },
    { Id: 53, name: 'Bella', prof: "Consultant", sub: "AWS" },
    { Id: 54, name: 'Caleb', prof: "Analyst", sub: "Google Cloud" },
    { Id: 55, name: 'Dina', prof: "Engineer", sub: "Oracle" },
    { Id: 56, name: 'Eli', prof: "Architect", sub: "Azure" },
    { Id: 57, name: 'Farah', prof: "Manager", sub: "GCP" },
    { Id: 58, name: 'Gus', prof: "Analyst", sub: "AWS" },
    { Id: 59, name: 'Hazel', prof: "Developer", sub: "SAP" },
    { Id: 60, name: 'Iris', prof: "Consultant", sub: "Oracle" },
    { Id: 61, name: 'Jason', prof: "Architect", sub: "Google Cloud" },
    { Id: 62, name: 'Kelly', prof: "Analyst", sub: "Azure" },
    { Id: 63, name: 'Luke', prof: "Engineer", sub: "GCP" },
    { Id: 64, name: 'Maddie', prof: "Developer", sub: "Oracle" },
    { Id: 65, name: 'Neil', prof: "Consultant", sub: "SAP" },
    { Id: 66, name: 'Owen', prof: "Manager", sub: "AWS" },
    { Id: 67, name: 'Pia', prof: "Analyst", sub: "Azure" },
    { Id: 68, name: 'Quincy', prof: "Engineer", sub: "Google Cloud" },
    { Id: 69, name: 'Rosa', prof: "Architect", sub: "Oracle" },
    { Id: 70, name: 'Sam', prof: "Consultant", sub: "SAP" },
    { Id: 71, name: 'Tina', prof: "Developer", sub: "AWS" },
    { Id: 72, name: 'Ulysses', prof: "Analyst", sub: "Azure" },
    { Id: 73, name: 'Vanessa', prof: "Manager", sub: "Google Cloud" },
    { Id: 74, name: 'Walt', prof: "Architect", sub: "Oracle" },
    { Id: 75, name: 'Xiomara', prof: "Engineer", sub: "GCP" },
    { Id: 76, name: 'Yolanda', prof: "Consultant", sub: "AWS" },
    { Id: 77, name: 'Zeke', prof: "Developer", sub: "SAP" },
    { Id: 78, name: 'Andy', prof: "Analyst", sub: "Azure" },
    { Id: 79, name: 'Beth', prof: "Engineer", sub: "Google Cloud" },
    { Id: 80, name: 'Clark', prof: "Manager", sub: "Oracle" },
    { Id: 81, name: 'Dora', prof: "Consultant", sub: "AWS" },
    { Id: 82, name: 'Evan', prof: "Architect", sub: "GCP" },
    { Id: 83, name: 'Faith', prof: "Analyst", sub: "Azure" },
    { Id: 84, name: 'Gary', prof: "Engineer", sub: "Oracle" },
    { Id: 85, name: 'Holly', prof: "Developer", sub: "Google Cloud" },
    { Id: 86, name: 'Ian', prof: "Consultant", sub: "AWS" },
    { Id: 87, name: 'Joy', prof: "Manager", sub: "SAP" },
    { Id: 88, name: 'Kyle', prof: "Analyst", sub: "Azure" },
    { Id: 89, name: 'Lana', prof: "Architect", sub: "GCP" },
    { Id: 90, name: 'Max', prof: "Engineer", sub: "Oracle" }
];
